### ISSUE TITLE
Sometimes the schedule and emails say the game is vs. yourself

### ISSUE THREAD

**Issue by Haliboot** [random-parts/Team-Sports-RSVP#19]
Probably depends on whether you are the away or home team. Example:

"James, will you attend the Dyslexia game? Monday, September 11 9:30 PM vs. Dislexia Untied"

(I thought I had already made an issue for this, but I don't see it. Sorry if it is a dupe)

**Comment by random-parts** [comment]
Was the team name manually changed from "Dyslexia Untied" to "Dyslexia"? Or is that the name that was set after the weblink was set?  If the weblink is reset, does it show the away teams properly?

The Team name in cell "A1" is used to determine "Home" & "Away" teams and will default to the Home team if no match is found.

**Comment by Haliboot** [comment]
Ah, makes sense. I think I probably manually changed it because SoccerZone
had misspelled it. They've corrected the spelling now.

Thanks,
- James

**Comment by random-parts** [comment]
SoccerZone misspelled `Dyslexia` . . . I cant get over the humor in that. It is funny in so many painfully personal ways

**Comment by Haliboot** [comment]
I thought about trying to point out the irony, but it didn't seem  likely
it would be understood or appreciated. :)
